chromadb:
  host: ${CHROMADB_HOST}
  port: ${CHROMADB_PORT}
  persistence: true
  collection: ${CHROMADB_COLLECTION}

arangodb:
  host: ${ARANGODB_HOST}
  port: ${ARANGODB_PORT}
  database: ${ARANGODB_DATABASE}
  username: ${ARANGODB_USERNAME}
  password: ${ARANGODB_PASSWORD}

openai:
  api_key: ${OPENAI_API_KEY}
  # ... other OpenAI-related configurations ...
  embedding_model: ${OPENAI_EMBEDDING_MODEL}
  language_model: ${OPENAI_LANGUAGE_MODEL}
  cache_ttl: 86400

document_preprocessing:
  default_chunk_size: 1000
  default_chunk_overlap: 200

vectorrag:
  default_top_k: 5

graphrag:
  max_depth: 2
  entity_similarity_threshold: 0.7

hybridrag:
  vector_weight: 0.5
  top_k: 5
  max_depth: 2

reranker:
  bm25_weight: 0.5
  semantic_weight: 0.5
  top_k: 10

logging:
  name: hybridrag
  path: /path/to/logs/hybridrag.log
  level: info
  debug_mode: false